
from constants import *
from define_scenario import *
from define_ve import *
from define_pve import *
from define_chem_classes import *
from define_comp_classes import *
from define_attributes_props import *

def define_comp(currentChemical):

    
	Degradation_Reaction_Sink_in_SW_LakeCadillac=Degradation_Reaction_Sink(Constants,containingScenario,currentChemical,SW_LakeCadillac)
	Degradation_Reaction_Sink_in_SW_LakeCadillac.Name="Degradation_Reaction_Sink_in_SW_LakeCadillac"
	Degradation_Reaction_Sink_in_SW_LakeCadillac.containingVolumeElement="SW_LakeCadillac"
	Degradation_Reaction_Sink_in_SW_LakeCadillac.Parcel_Name="LakeCadillac"
	Degradation_Reaction_Sink_in_SW_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	Degradation_Reaction_Sink_in_SW_LakeCadillac.Parcel_Area=4813963.143303742
	Degradation_Reaction_Sink_in_SW_LakeCadillac.Exterior_Boundary=0.0
	
	Flush_Rate_Sink_in_SW_LakeCadillac=Flush_Rate_Sink(Constants,containingScenario,currentChemical,SW_LakeCadillac)
	Flush_Rate_Sink_in_SW_LakeCadillac.Name="Flush_Rate_Sink_in_SW_LakeCadillac"
	Flush_Rate_Sink_in_SW_LakeCadillac.containingVolumeElement="SW_LakeCadillac"
	Flush_Rate_Sink_in_SW_LakeCadillac.Parcel_Name="LakeCadillac"
	Flush_Rate_Sink_in_SW_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	Flush_Rate_Sink_in_SW_LakeCadillac.Parcel_Area=4813963.143303742
	Flush_Rate_Sink_in_SW_LakeCadillac.Exterior_Boundary=0.0
	
	Degradation_Reaction_Sink_in_Sed_LakeCadillac=Degradation_Reaction_Sink(Constants,containingScenario,currentChemical,Sed_LakeCadillac)
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.Name="Degradation_Reaction_Sink_in_Sed_LakeCadillac"
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.containingVolumeElement="Sed_LakeCadillac"
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.Parcel_Name="LakeCadillac"
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.Parcel_Area=4813963.143303742
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.Exterior_Boundary=0.0
	### Note: This is an auto generated script

	Surface_water_in_SW_LakeCadillac=Surface_water(Constants,containingScenario,currentChemical,SW_LakeCadillac)
	Surface_water_in_SW_LakeCadillac.Name="Surface_water_in_SW_LakeCadillac"
	Surface_water_in_SW_LakeCadillac.containingVolumeElement="SW_LakeCadillac"
	Surface_water_in_SW_LakeCadillac.Parcel_Name="LakeCadillac"
	Surface_water_in_SW_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	Surface_water_in_SW_LakeCadillac.Parcel_Area=4813963.143303742
	Surface_water_in_SW_LakeCadillac.Exterior_Boundary=0.0
	
	Sediment_in_Sed_LakeCadillac=Sediment(Constants,containingScenario,currentChemical,Sed_LakeCadillac)
	Sediment_in_Sed_LakeCadillac.Name="Sediment_in_Sed_LakeCadillac"
	Sediment_in_Sed_LakeCadillac.containingVolumeElement="Sed_LakeCadillac"
	Sediment_in_Sed_LakeCadillac.Parcel_Name="LakeCadillac"
	Sediment_in_Sed_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	Sediment_in_Sed_LakeCadillac.Parcel_Area=4813963.143303742
	Sediment_in_Sed_LakeCadillac.Exterior_Boundary=0.0
	
	class Pseudo_Compartment:
		pass

	DryParticleSource_in_DryParticleSource_LakeCadillac=Pseudo_Compartment()
	DryParticleSource_in_DryParticleSource_LakeCadillac.Name="DryParticleSource_in_DryParticleSource_LakeCadillac"
	DryParticleSource_in_DryParticleSource_LakeCadillac.containingVolumeElement="DryParticleSource_LakeCadillac"
	DryParticleSource_in_DryParticleSource_LakeCadillac.Parcel_Name="LakeCadillac"
	DryParticleSource_in_DryParticleSource_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	DryParticleSource_in_DryParticleSource_LakeCadillac.Parcel_Area=4813963.143303742
	DryParticleSource_in_DryParticleSource_LakeCadillac.Exterior_Boundary=0.0
	DryParticleSource_in_DryParticleSource_LakeCadillac.Deposition_Rate={}
	DryParticleSource_in_DryParticleSource_LakeCadillac.category="Deposition | Dry | Particle"

	try:
		Surface_water_in_SW_LakeCadillac.AlgaeDensityInWaterColumn_g_L=1.23974964219194E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.Flushes_per_year=1.17313794554605
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.CurrentVelocity=0
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.AlgaeDensityInWaterColumn_g_L=1.08535940990977E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.Flushes_per_year=0.276267295275431
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.CurrentVelocity=0
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.SedimentResuspensionVelocity=9.64763202734353E-05
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.SedimentResuspensionVelocity=9.62414088491511E-05
	except:
		pass

	DryVaporSource_in_DryVaporSource_LakeCadillac=Pseudo_Compartment()
	DryVaporSource_in_DryVaporSource_LakeCadillac.Name="DryVaporSource_in_DryVaporSource_LakeCadillac"
	DryVaporSource_in_DryVaporSource_LakeCadillac.containingVolumeElement="DryVaporSource_LakeCadillac"
	DryVaporSource_in_DryVaporSource_LakeCadillac.Parcel_Name="LakeCadillac"
	DryVaporSource_in_DryVaporSource_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	DryVaporSource_in_DryVaporSource_LakeCadillac.Parcel_Area=4813963.143303742
	DryVaporSource_in_DryVaporSource_LakeCadillac.Exterior_Boundary=0.0
	DryVaporSource_in_DryVaporSource_LakeCadillac.Deposition_Rate={}
	DryVaporSource_in_DryVaporSource_LakeCadillac.category="Deposition | Dry | Vapor"

	try:
		Surface_water_in_SW_LakeCadillac.AlgaeDensityInWaterColumn_g_L=1.23974964219194E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.Flushes_per_year=1.17313794554605
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.CurrentVelocity=0
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.AlgaeDensityInWaterColumn_g_L=1.08535940990977E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.Flushes_per_year=0.276267295275431
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.CurrentVelocity=0
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.SedimentResuspensionVelocity=9.64763202734353E-05
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.SedimentResuspensionVelocity=9.62414088491511E-05
	except:
		pass

	WetParticleSource_in_WetParticleSource_LakeCadillac=Pseudo_Compartment()
	WetParticleSource_in_WetParticleSource_LakeCadillac.Name="WetParticleSource_in_WetParticleSource_LakeCadillac"
	WetParticleSource_in_WetParticleSource_LakeCadillac.containingVolumeElement="WetParticleSource_LakeCadillac"
	WetParticleSource_in_WetParticleSource_LakeCadillac.Parcel_Name="LakeCadillac"
	WetParticleSource_in_WetParticleSource_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	WetParticleSource_in_WetParticleSource_LakeCadillac.Parcel_Area=4813963.143303742
	WetParticleSource_in_WetParticleSource_LakeCadillac.Exterior_Boundary=0.0
	WetParticleSource_in_WetParticleSource_LakeCadillac.Deposition_Rate={}
	WetParticleSource_in_WetParticleSource_LakeCadillac.category="Deposition | Wet | Particle"

	try:
		Surface_water_in_SW_LakeCadillac.AlgaeDensityInWaterColumn_g_L=1.23974964219194E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.Flushes_per_year=1.17313794554605
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.CurrentVelocity=0
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.AlgaeDensityInWaterColumn_g_L=1.08535940990977E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.Flushes_per_year=0.276267295275431
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.CurrentVelocity=0
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.SedimentResuspensionVelocity=9.64763202734353E-05
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.SedimentResuspensionVelocity=9.62414088491511E-05
	except:
		pass

	WetVaporSource_in_WetVaporSource_LakeCadillac=Pseudo_Compartment()
	WetVaporSource_in_WetVaporSource_LakeCadillac.Name="WetVaporSource_in_WetVaporSource_LakeCadillac"
	WetVaporSource_in_WetVaporSource_LakeCadillac.containingVolumeElement="WetVaporSource_LakeCadillac"
	WetVaporSource_in_WetVaporSource_LakeCadillac.Parcel_Name="LakeCadillac"
	WetVaporSource_in_WetVaporSource_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	WetVaporSource_in_WetVaporSource_LakeCadillac.Parcel_Area=4813963.143303742
	WetVaporSource_in_WetVaporSource_LakeCadillac.Exterior_Boundary=0.0
	WetVaporSource_in_WetVaporSource_LakeCadillac.Deposition_Rate={}
	WetVaporSource_in_WetVaporSource_LakeCadillac.category="Deposition | Wet | Vapor"

	try:
		Surface_water_in_SW_LakeCadillac.AlgaeDensityInWaterColumn_g_L=1.23974964219194E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.Flushes_per_year=1.17313794554605
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.CurrentVelocity=0
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.AlgaeDensityInWaterColumn_g_L=1.08535940990977E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.Flushes_per_year=0.276267295275431
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.CurrentVelocity=0
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.SedimentResuspensionVelocity=9.64763202734353E-05
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.SedimentResuspensionVelocity=9.62414088491511E-05
	except:
		pass

#Add pseudo source dep rates to pseudo compartments

	try:
		WetParticleSource_in_WetParticleSource_W1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_W1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_W1.Deposition_Rate['Chem_Elemental_Mercury']=1.9020762035135754e-12*DryVaporSource_in_DryVaporSource_W1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_W1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_W1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_W1.Deposition_Rate['Chem_Elemental_Mercury']=1.7640885238421173e-14*WetVaporSource_in_WetVaporSource_W1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_SW2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_SW2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_SW2.Deposition_Rate['Chem_Elemental_Mercury']=3.828710098935972e-12*DryVaporSource_in_DryVaporSource_SW2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_SW2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_SW2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_SW2.Deposition_Rate['Chem_Elemental_Mercury']=2.0037085433389333e-14*WetVaporSource_in_WetVaporSource_SW2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_NW1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_NW1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_NW1.Deposition_Rate['Chem_Elemental_Mercury']=2.3934431983713296e-12*DryVaporSource_in_DryVaporSource_NW1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_NW1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_NW1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_NW1.Deposition_Rate['Chem_Elemental_Mercury']=1.656750732726092e-14*WetVaporSource_in_WetVaporSource_NW1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_NW2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_NW2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_NW2.Deposition_Rate['Chem_Elemental_Mercury']=2.214217268016036e-12*DryVaporSource_in_DryVaporSource_NW2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_NW2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_NW2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_NW2.Deposition_Rate['Chem_Elemental_Mercury']=1.2633225774909552e-14*WetVaporSource_in_WetVaporSource_NW2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_NE2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_NE2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_NE2.Deposition_Rate['Chem_Elemental_Mercury']=1.4401095140314853e-11*DryVaporSource_in_DryVaporSource_NE2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_NE2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_NE2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_NE2.Deposition_Rate['Chem_Elemental_Mercury']=5.6062057951174986e-14*WetVaporSource_in_WetVaporSource_NE2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_S1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_S1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_S1.Deposition_Rate['Chem_Elemental_Mercury']=8.40520191649555e-12*DryVaporSource_in_DryVaporSource_S1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_S1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_S1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_S1.Deposition_Rate['Chem_Elemental_Mercury']=4.887063655030801e-14*WetVaporSource_in_WetVaporSource_S1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_NE3.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_NE3.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_NE3.Deposition_Rate['Chem_Elemental_Mercury']=1.603011635865845e-11*DryVaporSource_in_DryVaporSource_NE3.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_NE3.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_NE3.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_NE3.Deposition_Rate['Chem_Elemental_Mercury']=5.352498288843258e-14*WetVaporSource_in_WetVaporSource_NE3.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_LakeCadillac.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_LakeCadillac.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_LakeCadillac.Deposition_Rate['Chem_Elemental_Mercury']=1.9986310746064338e-11*DryVaporSource_in_DryVaporSource_LakeCadillac.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_LakeCadillac.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_LakeCadillac.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_LakeCadillac.Deposition_Rate['Chem_Elemental_Mercury']=6.519507186858316e-14*WetVaporSource_in_WetVaporSource_LakeCadillac.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_SE1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_SE1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_SE1.Deposition_Rate['Chem_Elemental_Mercury']=5.518898775572286e-12*DryVaporSource_in_DryVaporSource_SE1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_SE1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_SE1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_SE1.Deposition_Rate['Chem_Elemental_Mercury']=2.1402388014297667e-14*WetVaporSource_in_WetVaporSource_SE1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_SE2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_SE2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_SE2.Deposition_Rate['Chem_Elemental_Mercury']=3.98631074606434e-12*DryVaporSource_in_DryVaporSource_SE2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_SE2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_SE2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_SE2.Deposition_Rate['Chem_Elemental_Mercury']=2.0343672322490008e-14*WetVaporSource_in_WetVaporSource_SE2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_S2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_S2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_S2.Deposition_Rate['Chem_Elemental_Mercury']=1.0230435774583618e-11*DryVaporSource_in_DryVaporSource_S2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_S2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_S2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_S2.Deposition_Rate['Chem_Elemental_Mercury']=3.263153091489848e-14*WetVaporSource_in_WetVaporSource_S2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_SW1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_SW1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_SW1.Deposition_Rate['Chem_Elemental_Mercury']=4.468780895885618e-12*DryVaporSource_in_DryVaporSource_SW1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_SW1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_SW1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_SW1.Deposition_Rate['Chem_Elemental_Mercury']=2.8351965928967985e-14*WetVaporSource_in_WetVaporSource_SW1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_N1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_N1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_N1.Deposition_Rate['Chem_Elemental_Mercury']=6.166370066164728e-12*DryVaporSource_in_DryVaporSource_N1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_N1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_N1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_N1.Deposition_Rate['Chem_Elemental_Mercury']=4.661282226785306e-14*WetVaporSource_in_WetVaporSource_N1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_N2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_N2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_N2.Deposition_Rate['Chem_Elemental_Mercury']=7.405119780971937e-12*DryVaporSource_in_DryVaporSource_N2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_N2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_N2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_N2.Deposition_Rate['Chem_Elemental_Mercury']=4.1026146475017115e-14*WetVaporSource_in_WetVaporSource_N2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_NE1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_NE1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_NE1.Deposition_Rate['Chem_Elemental_Mercury']=3.531240833088883e-11*DryVaporSource_in_DryVaporSource_NE1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_NE1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_NE1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_NE1.Deposition_Rate['Chem_Elemental_Mercury']=1.6006453505426813e-13*WetVaporSource_in_WetVaporSource_NE1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_E1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_E1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_E1.Deposition_Rate['Chem_Elemental_Mercury']=8.680355920602325e-12*DryVaporSource_in_DryVaporSource_E1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_E1.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_E1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_E1.Deposition_Rate['Chem_Elemental_Mercury']=3.8285420944558525e-14*WetVaporSource_in_WetVaporSource_E1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_LakeMitchell.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_LakeMitchell.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_LakeMitchell.Deposition_Rate['Chem_Elemental_Mercury']=3.411362080766599e-12*DryVaporSource_in_DryVaporSource_LakeMitchell.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_LakeMitchell.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_LakeMitchell.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_LakeMitchell.Deposition_Rate['Chem_Elemental_Mercury']=2.977052487481538e-14*WetVaporSource_in_WetVaporSource_LakeMitchell.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_E3.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_E3.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_E3.Deposition_Rate['Chem_Elemental_Mercury']=3.401627500190128e-12*DryVaporSource_in_DryVaporSource_E3.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_E3.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_E3.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_E3.Deposition_Rate['Chem_Elemental_Mercury']=2.092934823940984e-14*WetVaporSource_in_WetVaporSource_E3.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_E2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*WetParticleSource_in_WetParticleSource_E2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_E2.Deposition_Rate['Chem_Elemental_Mercury']=6.342853587206769e-12*DryVaporSource_in_DryVaporSource_E2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_E2.Deposition_Rate['Chem_Elemental_Mercury']=0.0*DryParticleSource_in_DryParticleSource_E2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_E2.Deposition_Rate['Chem_Elemental_Mercury']=3.1410615394188283e-14*WetVaporSource_in_WetVaporSource_E2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_W1.Deposition_Rate['Chem_Divalent_Mercury']=1.1440565822496006e-13*WetParticleSource_in_WetParticleSource_W1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_W1.Deposition_Rate['Chem_Divalent_Mercury']=2.1733059548254626e-10*DryVaporSource_in_DryVaporSource_W1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_W1.Deposition_Rate['Chem_Divalent_Mercury']=7.149258498745152e-11*DryParticleSource_in_DryParticleSource_W1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_W1.Deposition_Rate['Chem_Divalent_Mercury']=2.2406570841889122e-11*WetVaporSource_in_WetVaporSource_W1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_SW2.Deposition_Rate['Chem_Divalent_Mercury']=1.19828262086989e-13*WetParticleSource_in_WetParticleSource_SW2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_SW2.Deposition_Rate['Chem_Divalent_Mercury']=3.744782527534068e-10*DryVaporSource_in_DryVaporSource_SW2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_SW2.Deposition_Rate['Chem_Divalent_Mercury']=1.287486777425176e-10*DryParticleSource_in_DryParticleSource_SW2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_SW2.Deposition_Rate['Chem_Divalent_Mercury']=2.316918673386846e-11*WetVaporSource_in_WetVaporSource_SW2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_NW1.Deposition_Rate['Chem_Divalent_Mercury']=1.1171835237543656e-13*WetParticleSource_in_WetParticleSource_NW1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_NW1.Deposition_Rate['Chem_Divalent_Mercury']=2.5380578809736924e-10*DryVaporSource_in_DryVaporSource_NW1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_NW1.Deposition_Rate['Chem_Divalent_Mercury']=8.879060706576106e-11*DryParticleSource_in_DryParticleSource_NW1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_NW1.Deposition_Rate['Chem_Divalent_Mercury']=2.261605152775584e-11*WetVaporSource_in_WetVaporSource_NW1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_NW2.Deposition_Rate['Chem_Divalent_Mercury']=8.817287572113033e-14*WetParticleSource_in_WetParticleSource_NW2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_NW2.Deposition_Rate['Chem_Divalent_Mercury']=2.1593038036569865e-10*DryVaporSource_in_DryVaporSource_NW2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_NW2.Deposition_Rate['Chem_Divalent_Mercury']=7.56210032267527e-11*DryParticleSource_in_DryParticleSource_NW2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_NW2.Deposition_Rate['Chem_Divalent_Mercury']=1.7444020729441673e-11*WetVaporSource_in_WetVaporSource_NW2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_NE2.Deposition_Rate['Chem_Divalent_Mercury']=4.035592060232717e-13*WetParticleSource_in_WetParticleSource_NE2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_NE2.Deposition_Rate['Chem_Divalent_Mercury']=1.0431211498973307e-09*DryVaporSource_in_DryVaporSource_NE2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_NE2.Deposition_Rate['Chem_Divalent_Mercury']=4.945471138489619e-10*DryParticleSource_in_DryParticleSource_NE2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_NE2.Deposition_Rate['Chem_Divalent_Mercury']=8.514715947980836e-11*WetVaporSource_in_WetVaporSource_NE2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_S1.Deposition_Rate['Chem_Divalent_Mercury']=2.830937713894593e-13*WetParticleSource_in_WetParticleSource_S1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_S1.Deposition_Rate['Chem_Divalent_Mercury']=8.459958932238194e-10*DryVaporSource_in_DryVaporSource_S1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_S1.Deposition_Rate['Chem_Divalent_Mercury']=2.9185489390828203e-10*DryParticleSource_in_DryParticleSource_S1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_S1.Deposition_Rate['Chem_Divalent_Mercury']=5.995893223819301e-11*WetVaporSource_in_WetVaporSource_S1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_NE3.Deposition_Rate['Chem_Divalent_Mercury']=3.979009810631987e-13*WetParticleSource_in_WetParticleSource_NE3.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_NE3.Deposition_Rate['Chem_Divalent_Mercury']=1.8964179785535023e-09*DryVaporSource_in_DryVaporSource_NE3.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_NE3.Deposition_Rate['Chem_Divalent_Mercury']=5.686516084873375e-10*DryParticleSource_in_DryParticleSource_NE3.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_NE3.Deposition_Rate['Chem_Divalent_Mercury']=8.494182067077343e-11*WetVaporSource_in_WetVaporSource_NE3.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_LakeCadillac.Deposition_Rate['Chem_Divalent_Mercury']=4.181382614647501e-13*WetParticleSource_in_WetParticleSource_LakeCadillac.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_LakeCadillac.Deposition_Rate['Chem_Divalent_Mercury']=2.3093771389459273e-09*DryVaporSource_in_DryVaporSource_LakeCadillac.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_LakeCadillac.Deposition_Rate['Chem_Divalent_Mercury']=6.255304585900068e-10*DryParticleSource_in_DryParticleSource_LakeCadillac.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_LakeCadillac.Deposition_Rate['Chem_Divalent_Mercury']=9.041752224503764e-11*WetVaporSource_in_WetVaporSource_LakeCadillac.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_SE1.Deposition_Rate['Chem_Divalent_Mercury']=1.4741805460491293e-13*WetParticleSource_in_WetParticleSource_SE1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_SE1.Deposition_Rate['Chem_Divalent_Mercury']=8.599893528024944e-10*DryVaporSource_in_DryVaporSource_SE1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_SE1.Deposition_Rate['Chem_Divalent_Mercury']=1.9501102745455928e-10*DryParticleSource_in_DryParticleSource_SE1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_SE1.Deposition_Rate['Chem_Divalent_Mercury']=2.966613430679139e-11*WetVaporSource_in_WetVaporSource_SE1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_SE2.Deposition_Rate['Chem_Divalent_Mercury']=1.603515976800317e-13*WetParticleSource_in_WetParticleSource_SE2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_SE2.Deposition_Rate['Chem_Divalent_Mercury']=1.0533520659966138e-09*DryVaporSource_in_DryVaporSource_SE2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_SE2.Deposition_Rate['Chem_Divalent_Mercury']=1.6038041716200148e-10*DryParticleSource_in_DryParticleSource_SE2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_SE2.Deposition_Rate['Chem_Divalent_Mercury']=3.31164667315105e-11*WetVaporSource_in_WetVaporSource_SE2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_S2.Deposition_Rate['Chem_Divalent_Mercury']=2.1851699749030345e-13*WetParticleSource_in_WetParticleSource_S2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_S2.Deposition_Rate['Chem_Divalent_Mercury']=1.1969883641341548e-09*DryVaporSource_in_DryVaporSource_S2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_S2.Deposition_Rate['Chem_Divalent_Mercury']=3.403331051791011e-10*DryParticleSource_in_DryParticleSource_S2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_S2.Deposition_Rate['Chem_Divalent_Mercury']=4.553593429158112e-11*WetVaporSource_in_WetVaporSource_S2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_SW1.Deposition_Rate['Chem_Divalent_Mercury']=1.8075899307932162e-13*WetParticleSource_in_WetParticleSource_SW1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_SW1.Deposition_Rate['Chem_Divalent_Mercury']=4.860901969731539e-10*DryVaporSource_in_DryVaporSource_SW1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_SW1.Deposition_Rate['Chem_Divalent_Mercury']=1.6010342991862497e-10*DryParticleSource_in_DryParticleSource_SW1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_SW1.Deposition_Rate['Chem_Divalent_Mercury']=3.675412578903339e-11*WetVaporSource_in_WetVaporSource_SW1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_N1.Deposition_Rate['Chem_Divalent_Mercury']=3.1660506502395623e-13*WetParticleSource_in_WetParticleSource_N1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_N1.Deposition_Rate['Chem_Divalent_Mercury']=6.249235683321927e-10*DryVaporSource_in_DryVaporSource_N1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_N1.Deposition_Rate['Chem_Divalent_Mercury']=2.3414099931553734e-10*DryParticleSource_in_DryParticleSource_N1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_N1.Deposition_Rate['Chem_Divalent_Mercury']=6.815423226100845e-11*WetVaporSource_in_WetVaporSource_N1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_N2.Deposition_Rate['Chem_Divalent_Mercury']=3.1463381245722094e-13*WetParticleSource_in_WetParticleSource_N2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_N2.Deposition_Rate['Chem_Divalent_Mercury']=6.671813826146477e-10*DryVaporSource_in_DryVaporSource_N2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_N2.Deposition_Rate['Chem_Divalent_Mercury']=2.584312114989732e-10*DryParticleSource_in_DryParticleSource_N2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_N2.Deposition_Rate['Chem_Divalent_Mercury']=6.64016427104723e-11*WetVaporSource_in_WetVaporSource_N2.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_NE1.Deposition_Rate['Chem_Divalent_Mercury']=1.2354942798474624e-12*WetParticleSource_in_WetParticleSource_NE1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_NE1.Deposition_Rate['Chem_Divalent_Mercury']=3.7215214627945636e-09*DryVaporSource_in_DryVaporSource_NE1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_NE1.Deposition_Rate['Chem_Divalent_Mercury']=1.131025716241322e-09*DryParticleSource_in_DryParticleSource_NE1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_NE1.Deposition_Rate['Chem_Divalent_Mercury']=2.710863400801799e-10*WetVaporSource_in_WetVaporSource_NE1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_E1.Deposition_Rate['Chem_Divalent_Mercury']=2.948323066392883e-13*WetParticleSource_in_WetParticleSource_E1.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_E1.Deposition_Rate['Chem_Divalent_Mercury']=2.179671457905544e-09*DryVaporSource_in_DryVaporSource_E1.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_E1.Deposition_Rate['Chem_Divalent_Mercury']=3.233744010951403e-10*DryParticleSource_in_DryParticleSource_E1.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_E1.Deposition_Rate['Chem_Divalent_Mercury']=6.285763175906913e-11*WetVaporSource_in_WetVaporSource_E1.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_LakeMitchell.Deposition_Rate['Chem_Divalent_Mercury']=1.9764400734896788e-13*WetParticleSource_in_WetParticleSource_LakeMitchell.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_LakeMitchell.Deposition_Rate['Chem_Divalent_Mercury']=3.8145466335242627e-10*DryVaporSource_in_DryVaporSource_LakeMitchell.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_LakeMitchell.Deposition_Rate['Chem_Divalent_Mercury']=1.3242551965128425e-10*DryParticleSource_in_DryParticleSource_LakeMitchell.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_LakeMitchell.Deposition_Rate['Chem_Divalent_Mercury']=4.12089772686336e-11*WetVaporSource_in_WetVaporSource_LakeMitchell.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_E3.Deposition_Rate['Chem_Divalent_Mercury']=1.5106852232108904e-13*WetParticleSource_in_WetParticleSource_E3.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_E3.Deposition_Rate['Chem_Divalent_Mercury']=1.0020533880903492e-09*DryVaporSource_in_DryVaporSource_E3.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_E3.Deposition_Rate['Chem_Divalent_Mercury']=1.6621796334322002e-10*DryParticleSource_in_DryParticleSource_E3.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_E3.Deposition_Rate['Chem_Divalent_Mercury']=3.1181078409004486e-11*WetVaporSource_in_WetVaporSource_E3.Parcel_Area
	except:
		pass
	try:
		WetParticleSource_in_WetParticleSource_E2.Deposition_Rate['Chem_Divalent_Mercury']=2.297305705929936e-13*WetParticleSource_in_WetParticleSource_E2.Parcel_Area
	except:
		pass
	try:
		DryVaporSource_in_DryVaporSource_E2.Deposition_Rate['Chem_Divalent_Mercury']=1.6496795470101423e-09*DryVaporSource_in_DryVaporSource_E2.Parcel_Area
	except:
		pass
	try:
		DryParticleSource_in_DryParticleSource_E2.Deposition_Rate['Chem_Divalent_Mercury']=2.8279509675813575e-10*DryParticleSource_in_DryParticleSource_E2.Parcel_Area
	except:
		pass
	try:
		WetVaporSource_in_WetVaporSource_E2.Deposition_Rate['Chem_Divalent_Mercury']=4.864414162155435e-11*WetVaporSource_in_WetVaporSource_E2.Parcel_Area
	except:
		pass


	comp_objects_dict={}
	comp_objects_dict["Degradation_Reaction_Sink_in_SW_LakeCadillac"]=Degradation_Reaction_Sink_in_SW_LakeCadillac
	comp_objects_dict["Flush_Rate_Sink_in_SW_LakeCadillac"]=Flush_Rate_Sink_in_SW_LakeCadillac
	comp_objects_dict["Degradation_Reaction_Sink_in_Sed_LakeCadillac"]=Degradation_Reaction_Sink_in_Sed_LakeCadillac
	comp_objects_dict["Surface_water_in_SW_LakeCadillac"]=Surface_water_in_SW_LakeCadillac
	comp_objects_dict["Sediment_in_Sed_LakeCadillac"]=Sediment_in_Sed_LakeCadillac
	comp_objects_dict["DryParticleSource_in_DryParticleSource_LakeCadillac"]=DryParticleSource_in_DryParticleSource_LakeCadillac
	comp_objects_dict["DryVaporSource_in_DryVaporSource_LakeCadillac"]=DryVaporSource_in_DryVaporSource_LakeCadillac
	comp_objects_dict["WetParticleSource_in_WetParticleSource_LakeCadillac"]=WetParticleSource_in_WetParticleSource_LakeCadillac
	comp_objects_dict["WetVaporSource_in_WetVaporSource_LakeCadillac"]=WetVaporSource_in_WetVaporSource_LakeCadillac
	
	return(comp_objects_dict)