### note: this is an auto generated script
try:
	wetparticlesource_in_wetparticlesource_w1.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_w1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_w1.emission_rate['chem_elemental_mercury']=1.9020762035135754e-12*dryvaporsource_in_dryvaporsource_w1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_w1.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_w1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_w1.emission_rate['chem_elemental_mercury']=1.7640885238421173e-14*wetvaporsource_in_wetvaporsource_w1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_sw2.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_sw2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_sw2.emission_rate['chem_elemental_mercury']=3.828710098935972e-12*dryvaporsource_in_dryvaporsource_sw2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_sw2.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_sw2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_sw2.emission_rate['chem_elemental_mercury']=2.0037085433389333e-14*wetvaporsource_in_wetvaporsource_sw2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_nw1.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_nw1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_nw1.emission_rate['chem_elemental_mercury']=2.3934431983713296e-12*dryvaporsource_in_dryvaporsource_nw1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_nw1.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_nw1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_nw1.emission_rate['chem_elemental_mercury']=1.656750732726092e-14*wetvaporsource_in_wetvaporsource_nw1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_nw2.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_nw2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_nw2.emission_rate['chem_elemental_mercury']=2.214217268016036e-12*dryvaporsource_in_dryvaporsource_nw2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_nw2.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_nw2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_nw2.emission_rate['chem_elemental_mercury']=1.2633225774909552e-14*wetvaporsource_in_wetvaporsource_nw2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_ne2.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_ne2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_ne2.emission_rate['chem_elemental_mercury']=1.4401095140314853e-11*dryvaporsource_in_dryvaporsource_ne2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_ne2.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_ne2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_ne2.emission_rate['chem_elemental_mercury']=5.6062057951174986e-14*wetvaporsource_in_wetvaporsource_ne2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_s1.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_s1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_s1.emission_rate['chem_elemental_mercury']=8.40520191649555e-12*dryvaporsource_in_dryvaporsource_s1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_s1.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_s1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_s1.emission_rate['chem_elemental_mercury']=4.887063655030801e-14*wetvaporsource_in_wetvaporsource_s1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_ne3.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_ne3.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_ne3.emission_rate['chem_elemental_mercury']=1.603011635865845e-11*dryvaporsource_in_dryvaporsource_ne3.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_ne3.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_ne3.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_ne3.emission_rate['chem_elemental_mercury']=5.352498288843258e-14*wetvaporsource_in_wetvaporsource_ne3.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_lakecadillac.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_lakecadillac.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_lakecadillac.emission_rate['chem_elemental_mercury']=1.9986310746064338e-11*dryvaporsource_in_dryvaporsource_lakecadillac.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_lakecadillac.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_lakecadillac.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_lakecadillac.emission_rate['chem_elemental_mercury']=6.519507186858316e-14*wetvaporsource_in_wetvaporsource_lakecadillac.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_se1.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_se1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_se1.emission_rate['chem_elemental_mercury']=5.518898775572286e-12*dryvaporsource_in_dryvaporsource_se1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_se1.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_se1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_se1.emission_rate['chem_elemental_mercury']=2.1402388014297667e-14*wetvaporsource_in_wetvaporsource_se1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_se2.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_se2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_se2.emission_rate['chem_elemental_mercury']=3.98631074606434e-12*dryvaporsource_in_dryvaporsource_se2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_se2.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_se2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_se2.emission_rate['chem_elemental_mercury']=2.0343672322490008e-14*wetvaporsource_in_wetvaporsource_se2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_s2.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_s2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_s2.emission_rate['chem_elemental_mercury']=1.0230435774583618e-11*dryvaporsource_in_dryvaporsource_s2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_s2.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_s2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_s2.emission_rate['chem_elemental_mercury']=3.263153091489848e-14*wetvaporsource_in_wetvaporsource_s2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_sw1.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_sw1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_sw1.emission_rate['chem_elemental_mercury']=4.468780895885618e-12*dryvaporsource_in_dryvaporsource_sw1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_sw1.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_sw1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_sw1.emission_rate['chem_elemental_mercury']=2.8351965928967985e-14*wetvaporsource_in_wetvaporsource_sw1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_n1.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_n1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_n1.emission_rate['chem_elemental_mercury']=6.166370066164728e-12*dryvaporsource_in_dryvaporsource_n1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_n1.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_n1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_n1.emission_rate['chem_elemental_mercury']=4.661282226785306e-14*wetvaporsource_in_wetvaporsource_n1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_n2.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_n2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_n2.emission_rate['chem_elemental_mercury']=7.405119780971937e-12*dryvaporsource_in_dryvaporsource_n2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_n2.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_n2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_n2.emission_rate['chem_elemental_mercury']=4.1026146475017115e-14*wetvaporsource_in_wetvaporsource_n2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_ne1.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_ne1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_ne1.emission_rate['chem_elemental_mercury']=3.531240833088883e-11*dryvaporsource_in_dryvaporsource_ne1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_ne1.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_ne1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_ne1.emission_rate['chem_elemental_mercury']=1.6006453505426813e-13*wetvaporsource_in_wetvaporsource_ne1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_e1.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_e1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_e1.emission_rate['chem_elemental_mercury']=8.680355920602325e-12*dryvaporsource_in_dryvaporsource_e1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_e1.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_e1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_e1.emission_rate['chem_elemental_mercury']=3.8285420944558525e-14*wetvaporsource_in_wetvaporsource_e1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_lakemitchell.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_lakemitchell.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_lakemitchell.emission_rate['chem_elemental_mercury']=3.411362080766599e-12*dryvaporsource_in_dryvaporsource_lakemitchell.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_lakemitchell.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_lakemitchell.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_lakemitchell.emission_rate['chem_elemental_mercury']=2.977052487481538e-14*wetvaporsource_in_wetvaporsource_lakemitchell.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_e3.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_e3.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_e3.emission_rate['chem_elemental_mercury']=3.401627500190128e-12*dryvaporsource_in_dryvaporsource_e3.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_e3.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_e3.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_e3.emission_rate['chem_elemental_mercury']=2.092934823940984e-14*wetvaporsource_in_wetvaporsource_e3.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_e2.emission_rate['chem_elemental_mercury']=0.0*wetparticlesource_in_wetparticlesource_e2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_e2.emission_rate['chem_elemental_mercury']=6.342853587206769e-12*dryvaporsource_in_dryvaporsource_e2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_e2.emission_rate['chem_elemental_mercury']=0.0*dryparticlesource_in_dryparticlesource_e2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_e2.emission_rate['chem_elemental_mercury']=3.1410615394188283e-14*wetvaporsource_in_wetvaporsource_e2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_w1.emission_rate['chem_divalent_mercury']=1.1440565822496006e-13*wetparticlesource_in_wetparticlesource_w1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_w1.emission_rate['chem_divalent_mercury']=2.1733059548254626e-10*dryvaporsource_in_dryvaporsource_w1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_w1.emission_rate['chem_divalent_mercury']=7.149258498745152e-11*dryparticlesource_in_dryparticlesource_w1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_w1.emission_rate['chem_divalent_mercury']=2.2406570841889122e-11*wetvaporsource_in_wetvaporsource_w1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_sw2.emission_rate['chem_divalent_mercury']=1.19828262086989e-13*wetparticlesource_in_wetparticlesource_sw2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_sw2.emission_rate['chem_divalent_mercury']=3.744782527534068e-10*dryvaporsource_in_dryvaporsource_sw2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_sw2.emission_rate['chem_divalent_mercury']=1.287486777425176e-10*dryparticlesource_in_dryparticlesource_sw2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_sw2.emission_rate['chem_divalent_mercury']=2.316918673386846e-11*wetvaporsource_in_wetvaporsource_sw2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_nw1.emission_rate['chem_divalent_mercury']=1.1171835237543656e-13*wetparticlesource_in_wetparticlesource_nw1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_nw1.emission_rate['chem_divalent_mercury']=2.5380578809736924e-10*dryvaporsource_in_dryvaporsource_nw1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_nw1.emission_rate['chem_divalent_mercury']=8.879060706576106e-11*dryparticlesource_in_dryparticlesource_nw1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_nw1.emission_rate['chem_divalent_mercury']=2.261605152775584e-11*wetvaporsource_in_wetvaporsource_nw1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_nw2.emission_rate['chem_divalent_mercury']=8.817287572113033e-14*wetparticlesource_in_wetparticlesource_nw2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_nw2.emission_rate['chem_divalent_mercury']=2.1593038036569865e-10*dryvaporsource_in_dryvaporsource_nw2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_nw2.emission_rate['chem_divalent_mercury']=7.56210032267527e-11*dryparticlesource_in_dryparticlesource_nw2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_nw2.emission_rate['chem_divalent_mercury']=1.7444020729441673e-11*wetvaporsource_in_wetvaporsource_nw2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_ne2.emission_rate['chem_divalent_mercury']=4.035592060232717e-13*wetparticlesource_in_wetparticlesource_ne2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_ne2.emission_rate['chem_divalent_mercury']=1.0431211498973307e-09*dryvaporsource_in_dryvaporsource_ne2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_ne2.emission_rate['chem_divalent_mercury']=4.945471138489619e-10*dryparticlesource_in_dryparticlesource_ne2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_ne2.emission_rate['chem_divalent_mercury']=8.514715947980836e-11*wetvaporsource_in_wetvaporsource_ne2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_s1.emission_rate['chem_divalent_mercury']=2.830937713894593e-13*wetparticlesource_in_wetparticlesource_s1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_s1.emission_rate['chem_divalent_mercury']=8.459958932238194e-10*dryvaporsource_in_dryvaporsource_s1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_s1.emission_rate['chem_divalent_mercury']=2.9185489390828203e-10*dryparticlesource_in_dryparticlesource_s1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_s1.emission_rate['chem_divalent_mercury']=5.995893223819301e-11*wetvaporsource_in_wetvaporsource_s1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_ne3.emission_rate['chem_divalent_mercury']=3.979009810631987e-13*wetparticlesource_in_wetparticlesource_ne3.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_ne3.emission_rate['chem_divalent_mercury']=1.8964179785535023e-09*dryvaporsource_in_dryvaporsource_ne3.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_ne3.emission_rate['chem_divalent_mercury']=5.686516084873375e-10*dryparticlesource_in_dryparticlesource_ne3.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_ne3.emission_rate['chem_divalent_mercury']=8.494182067077343e-11*wetvaporsource_in_wetvaporsource_ne3.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_lakecadillac.emission_rate['chem_divalent_mercury']=4.181382614647501e-13*wetparticlesource_in_wetparticlesource_lakecadillac.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_lakecadillac.emission_rate['chem_divalent_mercury']=2.3093771389459273e-09*dryvaporsource_in_dryvaporsource_lakecadillac.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_lakecadillac.emission_rate['chem_divalent_mercury']=6.255304585900068e-10*dryparticlesource_in_dryparticlesource_lakecadillac.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_lakecadillac.emission_rate['chem_divalent_mercury']=9.041752224503764e-11*wetvaporsource_in_wetvaporsource_lakecadillac.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_se1.emission_rate['chem_divalent_mercury']=1.4741805460491293e-13*wetparticlesource_in_wetparticlesource_se1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_se1.emission_rate['chem_divalent_mercury']=8.599893528024944e-10*dryvaporsource_in_dryvaporsource_se1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_se1.emission_rate['chem_divalent_mercury']=1.9501102745455928e-10*dryparticlesource_in_dryparticlesource_se1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_se1.emission_rate['chem_divalent_mercury']=2.966613430679139e-11*wetvaporsource_in_wetvaporsource_se1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_se2.emission_rate['chem_divalent_mercury']=1.603515976800317e-13*wetparticlesource_in_wetparticlesource_se2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_se2.emission_rate['chem_divalent_mercury']=1.0533520659966138e-09*dryvaporsource_in_dryvaporsource_se2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_se2.emission_rate['chem_divalent_mercury']=1.6038041716200148e-10*dryparticlesource_in_dryparticlesource_se2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_se2.emission_rate['chem_divalent_mercury']=3.31164667315105e-11*wetvaporsource_in_wetvaporsource_se2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_s2.emission_rate['chem_divalent_mercury']=2.1851699749030345e-13*wetparticlesource_in_wetparticlesource_s2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_s2.emission_rate['chem_divalent_mercury']=1.1969883641341548e-09*dryvaporsource_in_dryvaporsource_s2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_s2.emission_rate['chem_divalent_mercury']=3.403331051791011e-10*dryparticlesource_in_dryparticlesource_s2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_s2.emission_rate['chem_divalent_mercury']=4.553593429158112e-11*wetvaporsource_in_wetvaporsource_s2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_sw1.emission_rate['chem_divalent_mercury']=1.8075899307932162e-13*wetparticlesource_in_wetparticlesource_sw1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_sw1.emission_rate['chem_divalent_mercury']=4.860901969731539e-10*dryvaporsource_in_dryvaporsource_sw1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_sw1.emission_rate['chem_divalent_mercury']=1.6010342991862497e-10*dryparticlesource_in_dryparticlesource_sw1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_sw1.emission_rate['chem_divalent_mercury']=3.675412578903339e-11*wetvaporsource_in_wetvaporsource_sw1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_n1.emission_rate['chem_divalent_mercury']=3.1660506502395623e-13*wetparticlesource_in_wetparticlesource_n1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_n1.emission_rate['chem_divalent_mercury']=6.249235683321927e-10*dryvaporsource_in_dryvaporsource_n1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_n1.emission_rate['chem_divalent_mercury']=2.3414099931553734e-10*dryparticlesource_in_dryparticlesource_n1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_n1.emission_rate['chem_divalent_mercury']=6.815423226100845e-11*wetvaporsource_in_wetvaporsource_n1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_n2.emission_rate['chem_divalent_mercury']=3.1463381245722094e-13*wetparticlesource_in_wetparticlesource_n2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_n2.emission_rate['chem_divalent_mercury']=6.671813826146477e-10*dryvaporsource_in_dryvaporsource_n2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_n2.emission_rate['chem_divalent_mercury']=2.584312114989732e-10*dryparticlesource_in_dryparticlesource_n2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_n2.emission_rate['chem_divalent_mercury']=6.64016427104723e-11*wetvaporsource_in_wetvaporsource_n2.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_ne1.emission_rate['chem_divalent_mercury']=1.2354942798474624e-12*wetparticlesource_in_wetparticlesource_ne1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_ne1.emission_rate['chem_divalent_mercury']=3.7215214627945636e-09*dryvaporsource_in_dryvaporsource_ne1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_ne1.emission_rate['chem_divalent_mercury']=1.131025716241322e-09*dryparticlesource_in_dryparticlesource_ne1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_ne1.emission_rate['chem_divalent_mercury']=2.710863400801799e-10*wetvaporsource_in_wetvaporsource_ne1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_e1.emission_rate['chem_divalent_mercury']=2.948323066392883e-13*wetparticlesource_in_wetparticlesource_e1.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_e1.emission_rate['chem_divalent_mercury']=2.179671457905544e-09*dryvaporsource_in_dryvaporsource_e1.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_e1.emission_rate['chem_divalent_mercury']=3.233744010951403e-10*dryparticlesource_in_dryparticlesource_e1.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_e1.emission_rate['chem_divalent_mercury']=6.285763175906913e-11*wetvaporsource_in_wetvaporsource_e1.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_lakemitchell.emission_rate['chem_divalent_mercury']=1.9764400734896788e-13*wetparticlesource_in_wetparticlesource_lakemitchell.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_lakemitchell.emission_rate['chem_divalent_mercury']=3.8145466335242627e-10*dryvaporsource_in_dryvaporsource_lakemitchell.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_lakemitchell.emission_rate['chem_divalent_mercury']=1.3242551965128425e-10*dryparticlesource_in_dryparticlesource_lakemitchell.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_lakemitchell.emission_rate['chem_divalent_mercury']=4.12089772686336e-11*wetvaporsource_in_wetvaporsource_lakemitchell.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_e3.emission_rate['chem_divalent_mercury']=1.5106852232108904e-13*wetparticlesource_in_wetparticlesource_e3.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_e3.emission_rate['chem_divalent_mercury']=1.0020533880903492e-09*dryvaporsource_in_dryvaporsource_e3.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_e3.emission_rate['chem_divalent_mercury']=1.6621796334322002e-10*dryparticlesource_in_dryparticlesource_e3.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_e3.emission_rate['chem_divalent_mercury']=3.1181078409004486e-11*wetvaporsource_in_wetvaporsource_e3.parcel_area
except:
	pass
try:
	wetparticlesource_in_wetparticlesource_e2.emission_rate['chem_divalent_mercury']=2.297305705929936e-13*wetparticlesource_in_wetparticlesource_e2.parcel_area
except:
	pass
try:
	dryvaporsource_in_dryvaporsource_e2.emission_rate['chem_divalent_mercury']=1.6496795470101423e-09*dryvaporsource_in_dryvaporsource_e2.parcel_area
except:
	pass
try:
	dryparticlesource_in_dryparticlesource_e2.emission_rate['chem_divalent_mercury']=2.8279509675813575e-10*dryparticlesource_in_dryparticlesource_e2.parcel_area
except:
	pass
try:
	wetvaporsource_in_wetvaporsource_e2.emission_rate['chem_divalent_mercury']=4.864414162155435e-11*wetvaporsource_in_wetvaporsource_e2.parcel_area
except:
	pass
