
from constants import *
from define_scenario import *
from define_ve import *
from define_pve import *
from define_chem_classes import *
from define_comp_classes import *
from define_attributes_props import *

def define_comp(currentChemical):

    
	Degradation_Reaction_Sink_in_SW_LakeCadillac=Degradation_Reaction_Sink(Constants,containingScenario,currentChemical,SW_LakeCadillac)
	Degradation_Reaction_Sink_in_SW_LakeCadillac.Name="Degradation_Reaction_Sink_in_SW_LakeCadillac"
	Degradation_Reaction_Sink_in_SW_LakeCadillac.containingVolumeElement="SW_LakeCadillac"
	Degradation_Reaction_Sink_in_SW_LakeCadillac.Parcel_Name="LakeCadillac"
	Degradation_Reaction_Sink_in_SW_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	Degradation_Reaction_Sink_in_SW_LakeCadillac.Parcel_Area=4813963.143303742
	Degradation_Reaction_Sink_in_SW_LakeCadillac.Exterior_Boundary=0.0
	
	Flush_Rate_Sink_in_SW_LakeCadillac=Flush_Rate_Sink(Constants,containingScenario,currentChemical,SW_LakeCadillac)
	Flush_Rate_Sink_in_SW_LakeCadillac.Name="Flush_Rate_Sink_in_SW_LakeCadillac"
	Flush_Rate_Sink_in_SW_LakeCadillac.containingVolumeElement="SW_LakeCadillac"
	Flush_Rate_Sink_in_SW_LakeCadillac.Parcel_Name="LakeCadillac"
	Flush_Rate_Sink_in_SW_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	Flush_Rate_Sink_in_SW_LakeCadillac.Parcel_Area=4813963.143303742
	Flush_Rate_Sink_in_SW_LakeCadillac.Exterior_Boundary=0.0
	
	Degradation_Reaction_Sink_in_Sed_LakeCadillac=Degradation_Reaction_Sink(Constants,containingScenario,currentChemical,Sed_LakeCadillac)
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.Name="Degradation_Reaction_Sink_in_Sed_LakeCadillac"
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.containingVolumeElement="Sed_LakeCadillac"
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.Parcel_Name="LakeCadillac"
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.Parcel_Area=4813963.143303742
	Degradation_Reaction_Sink_in_Sed_LakeCadillac.Exterior_Boundary=0.0
	### Note: This is an auto generated script

	Surface_water_in_SW_LakeCadillac=Surface_water(Constants,containingScenario,currentChemical,SW_LakeCadillac)
	Surface_water_in_SW_LakeCadillac.Name="Surface_water_in_SW_LakeCadillac"
	Surface_water_in_SW_LakeCadillac.containingVolumeElement="SW_LakeCadillac"
	Surface_water_in_SW_LakeCadillac.Parcel_Name="LakeCadillac"
	Surface_water_in_SW_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	Surface_water_in_SW_LakeCadillac.Parcel_Area=4813963.143303742
	Surface_water_in_SW_LakeCadillac.Exterior_Boundary=0.0
	
	Sediment_in_Sed_LakeCadillac=Sediment(Constants,containingScenario,currentChemical,Sed_LakeCadillac)
	Sediment_in_Sed_LakeCadillac.Name="Sediment_in_Sed_LakeCadillac"
	Sediment_in_Sed_LakeCadillac.containingVolumeElement="Sed_LakeCadillac"
	Sediment_in_Sed_LakeCadillac.Parcel_Name="LakeCadillac"
	Sediment_in_Sed_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	Sediment_in_Sed_LakeCadillac.Parcel_Area=4813963.143303742
	Sediment_in_Sed_LakeCadillac.Exterior_Boundary=0.0
	
	class Pseudo_Compartment:
		pass

	DryParticleSource_in_DryParticleSource_LakeCadillac=Pseudo_Compartment()
	DryParticleSource_in_DryParticleSource_LakeCadillac.Name="DryParticleSource_in_DryParticleSource_LakeCadillac"
	DryParticleSource_in_DryParticleSource_LakeCadillac.containingVolumeElement="DryParticleSource_LakeCadillac"
	DryParticleSource_in_DryParticleSource_LakeCadillac.Parcel_Name="LakeCadillac"
	DryParticleSource_in_DryParticleSource_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	DryParticleSource_in_DryParticleSource_LakeCadillac.Parcel_Area=4813963.143303742
	DryParticleSource_in_DryParticleSource_LakeCadillac.Exterior_Boundary=0.0
	DryParticleSource_in_DryParticleSource_LakeCadillac.Emission_Rate={}
	DryParticleSource_in_DryParticleSource_LakeCadillac.category="Deposition | Dry | Particle"

	try:
		Surface_water_in_SW_LakeCadillac.AlgaeDensityInWaterColumn_g_L=1.23974964219194E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.Flushes_per_year=1.17313794554605
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.CurrentVelocity=0
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.AlgaeDensityInWaterColumn_g_L=1.08535940990977E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.Flushes_per_year=0.276267295275431
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.CurrentVelocity=0
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.SedimentResuspensionVelocity=9.64763202734353E-05
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.SedimentResuspensionVelocity=9.62414088491511E-05
	except:
		pass

	DryVaporSource_in_DryVaporSource_LakeCadillac=Pseudo_Compartment()
	DryVaporSource_in_DryVaporSource_LakeCadillac.Name="DryVaporSource_in_DryVaporSource_LakeCadillac"
	DryVaporSource_in_DryVaporSource_LakeCadillac.containingVolumeElement="DryVaporSource_LakeCadillac"
	DryVaporSource_in_DryVaporSource_LakeCadillac.Parcel_Name="LakeCadillac"
	DryVaporSource_in_DryVaporSource_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	DryVaporSource_in_DryVaporSource_LakeCadillac.Parcel_Area=4813963.143303742
	DryVaporSource_in_DryVaporSource_LakeCadillac.Exterior_Boundary=0.0
	DryVaporSource_in_DryVaporSource_LakeCadillac.Emission_Rate={}
	DryVaporSource_in_DryVaporSource_LakeCadillac.category="Deposition | Dry | Vapor"

	try:
		Surface_water_in_SW_LakeCadillac.AlgaeDensityInWaterColumn_g_L=1.23974964219194E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.Flushes_per_year=1.17313794554605
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.CurrentVelocity=0
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.AlgaeDensityInWaterColumn_g_L=1.08535940990977E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.Flushes_per_year=0.276267295275431
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.CurrentVelocity=0
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.SedimentResuspensionVelocity=9.64763202734353E-05
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.SedimentResuspensionVelocity=9.62414088491511E-05
	except:
		pass

	WetParticleSource_in_WetParticleSource_LakeCadillac=Pseudo_Compartment()
	WetParticleSource_in_WetParticleSource_LakeCadillac.Name="WetParticleSource_in_WetParticleSource_LakeCadillac"
	WetParticleSource_in_WetParticleSource_LakeCadillac.containingVolumeElement="WetParticleSource_LakeCadillac"
	WetParticleSource_in_WetParticleSource_LakeCadillac.Parcel_Name="LakeCadillac"
	WetParticleSource_in_WetParticleSource_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	WetParticleSource_in_WetParticleSource_LakeCadillac.Parcel_Area=4813963.143303742
	WetParticleSource_in_WetParticleSource_LakeCadillac.Exterior_Boundary=0.0
	WetParticleSource_in_WetParticleSource_LakeCadillac.Emission_Rate={}
	WetParticleSource_in_WetParticleSource_LakeCadillac.category="Deposition | Wet | Particle"

	try:
		Surface_water_in_SW_LakeCadillac.AlgaeDensityInWaterColumn_g_L=1.23974964219194E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.Flushes_per_year=1.17313794554605
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.CurrentVelocity=0
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.AlgaeDensityInWaterColumn_g_L=1.08535940990977E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.Flushes_per_year=0.276267295275431
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.CurrentVelocity=0
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.SedimentResuspensionVelocity=9.64763202734353E-05
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.SedimentResuspensionVelocity=9.62414088491511E-05
	except:
		pass

	WetVaporSource_in_WetVaporSource_LakeCadillac=Pseudo_Compartment()
	WetVaporSource_in_WetVaporSource_LakeCadillac.Name="WetVaporSource_in_WetVaporSource_LakeCadillac"
	WetVaporSource_in_WetVaporSource_LakeCadillac.containingVolumeElement="WetVaporSource_LakeCadillac"
	WetVaporSource_in_WetVaporSource_LakeCadillac.Parcel_Name="LakeCadillac"
	WetVaporSource_in_WetVaporSource_LakeCadillac.Parcel_Points="p9 p10 p11 p12 p13 p14"
	WetVaporSource_in_WetVaporSource_LakeCadillac.Parcel_Area=4813963.143303742
	WetVaporSource_in_WetVaporSource_LakeCadillac.Exterior_Boundary=0.0
	WetVaporSource_in_WetVaporSource_LakeCadillac.Emission_Rate={}
	WetVaporSource_in_WetVaporSource_LakeCadillac.category="Deposition | Wet | Vapor"

	try:
		Surface_water_in_SW_LakeCadillac.AlgaeDensityInWaterColumn_g_L=1.23974964219194E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.Flushes_per_year=1.17313794554605
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeCadillac.CurrentVelocity=0
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.AlgaeDensityInWaterColumn_g_L=1.08535940990977E-02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorideConcentration_mg_L=7
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.ChlorophyllConcentration_mg_L=0.003
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.pH=8.5
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.SuspendedSedimentConcentration=0.05
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.WaterTemperature_K=286.15
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.Flushes_per_year=0.276267295275431
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.IsFlowing=False
	except:
		pass
	try:
		Surface_water_in_SW_LakeMitchell.CurrentVelocity=0
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeCadillac.SedimentResuspensionVelocity=9.64763202734353E-05
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.OrganicCarbonContent=0.02
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.pH=7.3
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.rho=2600
	except:
		pass
	try:
		Sediment_in_Sed_LakeMitchell.SedimentResuspensionVelocity=9.62414088491511E-05
	except:
		pass


	comp_objects_dict={}
	comp_objects_dict["Degradation_Reaction_Sink_in_SW_LakeCadillac"]=Degradation_Reaction_Sink_in_SW_LakeCadillac
	comp_objects_dict["Flush_Rate_Sink_in_SW_LakeCadillac"]=Flush_Rate_Sink_in_SW_LakeCadillac
	comp_objects_dict["Degradation_Reaction_Sink_in_Sed_LakeCadillac"]=Degradation_Reaction_Sink_in_Sed_LakeCadillac
	comp_objects_dict["Surface_water_in_SW_LakeCadillac"]=Surface_water_in_SW_LakeCadillac
	comp_objects_dict["Sediment_in_Sed_LakeCadillac"]=Sediment_in_Sed_LakeCadillac
	comp_objects_dict["DryParticleSource_in_DryParticleSource_LakeCadillac"]=DryParticleSource_in_DryParticleSource_LakeCadillac
	comp_objects_dict["DryVaporSource_in_DryVaporSource_LakeCadillac"]=DryVaporSource_in_DryVaporSource_LakeCadillac
	comp_objects_dict["WetParticleSource_in_WetParticleSource_LakeCadillac"]=WetParticleSource_in_WetParticleSource_LakeCadillac
	comp_objects_dict["WetVaporSource_in_WetVaporSource_LakeCadillac"]=WetVaporSource_in_WetVaporSource_LakeCadillac
	
	return(comp_objects_dict)