DELETE FROM custom_parameter;
DELETE FROM parameter_definition;
DELETE FROM transport_process;
DELETE FROM formula_argument;
DELETE FROM formula;
DELETE FROM parameter_domain;
DELETE FROM compartment_link;
DELETE FROM compartment;
UPDATE media SET parent_id = NULL;
DELETE FROM media;
DELETE FROM volume_element;
DELETE FROM parcel;
DELETE FROM scenario_chemicals;
DELETE FROM chemical;
DELETE FROM scenario_load_run_proc;
DELETE FROM scenario_permissions;
DELETE FROM scenario;
-- DELETE FROM user WHERE id != 1;