ARG PYTRIM_GETFLOW_BUILD_PLATFORM="linux/amd64"

# h/t https://gis.stackexchange.com/questions/462843/setting-up-qgis-python-scripts-in-docker-container
#
# start with base Python image
# FROM python:3.12-alpine
# start with QGIS image
# FROM qgis/qgis
# FROM --platform=linux/amd64 qgis/qgis
FROM --platform=${PYTRIM_GETFLOW_BUILD_PLATFORM} qgis/qgis:4.2-questing

# Set environment variables for QGIS
ENV QGIS_PREFIX_PATH=/usr
ENV QT_QPA_PLATFORM=offscreen
ENV XDG_RUNTIME_DIR=/tmp/runtime-root

WORKDIR /app

# install numpy, pandas, etc. qgis.core installed by virtue of our base image.
# note - pip install doesn't work on this image, but this does:

# RUN apt install -y python3-pandas
# RUN apt install -y python3-numpy
# RUN apt install -y python3-boto3
# RUN apt install -y python3-shapely

# take 2, Feb 2025
COPY requirements.txt /tmp/requirements.txt
RUN python3 -m venv /app/getflow_venv

RUN /app/getflow_venv/bin/pip install --upgrade pip

# need git for flask-api; unzip + saga needed for processing plugins
RUN apt-get update && apt-get upgrade -y \
      && apt-get install -y git unzip saga \
      && rm -rf /var/lib/apt/lists/*

RUN /app/getflow_venv/bin/pip install -r /tmp/requirements.txt

# pip is not needed at runtime; dropping it removes its vendored libs
RUN /app/getflow_venv/bin/pip uninstall -y pip


# copy getflow src, supporting .tif, etc. in;
# you need to have run /docker/getflow/prepare_dockerized.py first!!!
# COPY temp/ /tmp/pytrim_getflow_src/
COPY temp/ /app/pytrim_getflow_src/


# perform GIS setup
WORKDIR /usr/share/qgis/python/plugins
# RUN mv /app/pytrim_getflow_src/processing_saga_nextgen-1.0.0.zip /usr/share/qgis/python/plugins
RUN mv /app/pytrim_getflow_src/processing_saga_nextgen-1.0.0.zip .

RUN unzip processing_saga_nextgen-1.0.0.zip

RUN rm processing_saga_nextgen-1.0.0.zip

# not entirely sure why we need this twice ("plugins"), but seems like we do?
RUN qgis_process plugins enable processing_saga_nextgen

RUN qgis_process plugins



# Logging within the container will update in real time rather than in chunks
ENV PYTHONUNBUFFERED=1


WORKDIR /app/pytrim_getflow_src

# A) install bash and let us peek around by attaching
# RUN apk add --no-cache bash
# CMD ["bash"]

# B) or, run the actual getflow code and quit when done
# old - builtin OS-managed version; has qgis but no other needed pytrim packages
# CMD ["python3", "getflow_entrypoint.py" ]
# new: use the virtual environment
CMD ["/app/getflow_venv/bin/python3", "getflow_entrypoint.py"]
