"""empty message

Revision ID: 12f3b3bc93f9
Revises: 
Create Date: 2021-10-13 15:59:53.599382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f3b3bc93f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cas_number', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=240), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cas_number')
    )
    op.create_table('formula',
    sa.Column('equation', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_process',
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('algorithm_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=240), nullable=False),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('output_chemical_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['output_chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['algorithm_id'], ['formula.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('can_emit', sa.Boolean(), nullable=False),
    sa.Column('can_absorb', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parameter_domain',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'requirements')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=40), nullable=True),
    sa.Column('current_login_ip', sa.String(length=40), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('formula_argument',
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['parameter_domain.id'], ),
    sa.ForeignKeyConstraint(['formula_id'], ['formula.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter_definition',
    sa.Column('variable_name', sa.String(length=60), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('default_value', sa.Float(), nullable=True),
    sa.Column('default_unit', sa.String(length=60), nullable=True),
    sa.Column('default_formula_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['default_formula_id'], ['formula.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['parameter_domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('scenario',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_table('team',
    # sa.Column('scenario_id', sa.Integer(), nullable=False),
    # sa.Column('member_id', sa.Integer(), nullable=False),
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    # sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('scenario_id', 'member_id')
    # )
    op.create_table('custom_parameter',
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('formula_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['parameter_definition.id'], ),
    sa.ForeignKeyConstraint(['formula_id'], ['formula.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcel',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('vertices', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'name')
    )
    op.create_table('scenario_chemicals',
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('chemical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.UniqueConstraint('scenario_id', 'chemical_id')
    )
    op.create_table('volume_element',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parcel_id', sa.Integer(), nullable=False),
    sa.Column('top', sa.Float(), nullable=False),
    sa.Column('bottom', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_id', 'name')
    )
    op.create_table('compartment',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('volume_element_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['volume_element_id'], ['volume_element.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volume_element_id', 'name')
    )
    op.create_table('compartment_link',
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['compartment.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['compartment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'receiver_id')
    )
    op.create_table('api_key',
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Unicode(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key')
    op.drop_table('compartment')
    op.drop_table('volume_element')
    op.drop_table('scenario_chemicals')
    op.drop_table('parcel')
    op.drop_table('custom_parameter')
    # op.drop_table('team')
    op.drop_table('scenario')
    op.drop_table('roles_users')
    op.drop_table('parameter_definition')
    op.drop_table('formula_argument')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('parameter_domain')
    op.drop_table('media')
    op.drop_table('formula')
    op.drop_table('chemical')
    # ### end Alembic commands ###
