"""
scenario_permissions table

Revision ID: 81e92f9ff252
Revises: 287d3ddae792
Create Date: 2025-09-24 14:53:15.742160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e92f9ff252'
down_revision = '287d3ddae792'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.engine.reflection.Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    if 'scenario_permissions' not in tables:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('scenario_permissions',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('scenario_id', sa.Integer(), nullable=False),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'scenario_id')
        )
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_permissions')
    # ### end Alembic commands ###
