"""empty message

Revision ID: 4416c27f2844
Revises: 90beadf3f7d6
Create Date: 2025-10-22 08:06:36.107624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4416c27f2844'
down_revision = '90beadf3f7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_custom_parameter_requirements', 'custom_parameter', [sa.text('substr(requirements, 1, 255)')], unique=False)
    op.create_index('idx_parameter_domain_requirements', 'parameter_domain', [sa.text('substr(requirements, 1, 255)')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_parameter_domain_requirements', table_name='parameter_domain')
    op.drop_index('idx_custom_parameter_requirements', table_name='custom_parameter')
    # ### end Alembic commands ###
