"""empty message

Revision ID: e5524555573a
Revises: 81e92f9ff252
Create Date: 2021-10-13 15:59:53.599382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5524555573a'
down_revision = '4416c27f2844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mirc_scenario',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=800), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['mirc_scenario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('mirc_scenario_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mirc_scenario_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['mirc_scenario_id'], ['mirc_scenario.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mirc_scenario_id')
    )
    op.create_table('mirc_simulation',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('trim_scenario_id', sa.Integer(), nullable=False),
    sa.Column('mirc_scenario_id', sa.Integer(), nullable=False),
    sa.Column('chemical_id', sa.Integer(), nullable=False),
    sa.Column('use_baf', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['trim_scenario_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['mirc_scenario_id'], ['mirc_scenario.id'], ),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mirc_life_stage',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('duration_unit', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mirc_percentile',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mirc_product',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_food', sa.Boolean(), nullable=False),
    sa.Column('is_feed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['mirc_product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mirc_toxicity_effect',
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('mirc_parameter',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('variable', sa.String(length=36), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('chemical_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('life_stage_id', sa.Integer(), nullable=True),
    sa.Column('percentile_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['mirc_product.id'], ),
    sa.ForeignKeyConstraint(['life_stage_id'], ['mirc_life_stage.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['mirc_product.id'], ),
    sa.ForeignKeyConstraint(['percentile_id'], ['mirc_percentile.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['mirc_scenario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'chemical_id', 'media_id', 'life_stage_id', 'percentile_id', 'food_id', 'name')
    )
    op.create_table('mirc_parameter_toxicity',
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('toxicity_effect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['mirc_parameter.id'], ),
    sa.ForeignKeyConstraint(['toxicity_effect_id'], ['mirc_toxicity_effect.id'], )
    )
    op.create_table('mirc_simulation_consumption_breakdown',
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('subfood_id', sa.Integer(), nullable=False),
    sa.Column('fraction', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['mirc_simulation.id'], ),
    sa.ForeignKeyConstraint(['subfood_id'], ['mirc_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mirc_simulation_parameter',
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('variable', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['mirc_simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mirc_simulation_percentile',
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('percentile_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['mirc_product.id'], ),
    sa.ForeignKeyConstraint(['percentile_id'], ['mirc_percentile.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['mirc_simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mirc_simulation_percentile')
    op.drop_table('mirc_simulation_parameter')
    op.drop_table('mirc_simulation_consumption_breakdown')
    op.drop_table('mirc_parameter_toxicity')
    op.drop_table('mirc_parameter')
    op.drop_table('mirc_toxicity_effect')
    op.drop_table('mirc_product')
    op.drop_table('mirc_percentile')
    op.drop_table('mirc_life_stage')
    op.drop_table('mirc_simulation')
    op.drop_table('mirc_scenario')
    # ### end Alembic commands ###
