"""empty message

Revision ID: 9cb7ef60fdb6
Revises: 3981a8f1cf7d
Create Date: 2021-08-27 09:16:00.683609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb7ef60fdb6'
down_revision = '3981a8f1cf7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('vertices', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'name')
    )
    op.create_table('volume_element',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parcel_id', sa.Integer(), nullable=False),
    sa.Column('top', sa.Float(), nullable=False),
    sa.Column('bottom', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_id', 'name')
    )
    op.create_table('compartment',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('volume_element_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['volume_element_id'], ['volume_element.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volume_element_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compartment')
    op.drop_table('volume_element')
    op.drop_table('parcel')
    # ### end Alembic commands ###
