"""empty message

Revision ID: f1ad41a8d389
Revises: 9cb7ef60fdb6
Create Date: 2021-09-02 13:48:00.609925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ad41a8d389'
down_revision = '9cb7ef60fdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cas_number', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=240), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cas_number')
    )
    op.create_table('chemical_parameters',
    sa.Column('chemical_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('variable', sa.String(length=36), nullable=True),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.Column('_val', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_chemicals',
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('chemical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.UniqueConstraint('scenario_id', 'chemical_id')
    )
    op.create_table('scenario_parameters',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('variable', sa.String(length=36), nullable=True),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.Column('_val', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volume_element_parameters',
    sa.Column('volume_element_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('variable', sa.String(length=36), nullable=True),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.Column('_val', sa.JSON(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['volume_element_id'], ['volume_element.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compartment_parameters',
    sa.Column('compartment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('variable', sa.String(length=36), nullable=True),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.Column('_val', sa.JSON(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['compartment_id'], ['compartment.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compartment_parameters')
    op.drop_table('volume_element_parameters')
    op.drop_table('scenario_parameters')
    op.drop_table('scenario_chemicals')
    op.drop_table('chemical_parameters')
    op.drop_table('chemical')
    # ### end Alembic commands ###
