name: Sync pyTRIM EPA GitHub Mirror
on: [push, workflow_dispatch]
concurrency:
  group: mirror_repo
jobs:
  mirror_repo:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ICF-Corp/trim-builder' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add SSH Private Keys
        run: |
          touch ~/.ssh/authorized_keys
          echo "${{ secrets.TRIM_SOURCE_SSH_PRIVATE_KEY }}" >> ~/.ssh/authorized_keys
          echo "${{ secrets.TRIM_MIRROR_SSH_PRIVATE_KEY }}" >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

      - name: Clone Source
        run: cd ~ && git clone --bare git@github.com:ICF-Corp/trim-builder.git

      - name: Push Mirror
        run: cd ~/trim-builder.git && git push --mirror git@github.com:USEPA/pyTRIM_EPA.git
